/// <reference types="vitest" />
import { defineConfig, type Plugin } from 'vitest/config';
import react from '@vitejs/plugin-react-swc';
import { resolve } from 'path';

/**
 * Stubs the wasm-pack generated WASM client JS file that doesn't exist in CI
 * (built by wasm-pack from Rust, not by npm run build). Prevents Vite's import
 * analysis from failing when resolving transitive imports through the WASM client.
 */
function stubWasmClient(): Plugin {
  return {
    name: 'stub-wasm-client',
    resolveId(id) {
      if (id.includes('citadel_internal_service_wasm_client')) {
        return { id: '\0wasm-stub', moduleSideEffects: false };
      }
    },
    load(id) {
      if (id === '\0wasm-stub') {
        return 'export default {}';
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), stubWasmClient()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    // Named rather than excluded. `**/*.test.ts` minus a list of directories
    // was whack-a-mole: every Playwright spec added anywhere under
    // integration-tests/ arrived here as a vitest failure.
    //
    // The integration SPECS are standalone scripts driven by their own runner
    // and by Playwright. Their `src/lib/` helpers are ordinary modules, and
    // excluding the whole tree meant none of them could have a unit test --
    // which is why the console-line formatter shipped cutting a CID in half
    // for as long as it did.
    include: [
      'src/**/*.{test,spec}.{ts,tsx}',
      // The gate scripts have tests too, and the first draft of this list
      // dropped them: 342 files before, 342 after, one swapped for another.
      // check-every-test-runs.mjs exists because of that.
      'scripts/**/*.{test,spec}.{ts,tsx}',
      'integration-tests/src/lib/**/*.{test,spec}.ts',
    ],
    exclude: ['**/node_modules/**', '**/dist/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      // Generated by vite-plugin-pwa at build time, so it cannot resolve here.
      // Without this the import fails before any vi.mock can intervene, and the
      // whole upgrade path is untestable.
      'virtual:pwa-register/react': resolve(__dirname, './src/test/pwa-register-stub.ts'),
      'virtual:pwa-register': resolve(__dirname, './src/test/pwa-register-stub.ts'),
    },
  },
});
