/**
 * The upgrade path. `registerType: 'prompt'` means a new build does NOTHING
 * until the user is offered a reload and takes it, so if this prompt is silent
 * an installed app sits on a stale bundle forever — the failure is invisible
 * precisely because nothing appears.
 *
 * The real Sonner surface is rendered rather than asserting on a mocked toast
 * call: the part most likely to break quietly is the action button, which only
 * exists if the `{label, onClick}` shape the component passes survives the
 * wrapper into Sonner. Asserting `toast` was called with the right object would
 * still pass if that contract broke.
 *
 * Only `virtual:pwa-register/react` is mocked — it is generated by the build and
 * cannot exist under vitest, and it is the seam the whole flow hangs from.
 */
import { describe, it, expect, beforeEach, vi   } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { render, screen, act , type RenderResult } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { UserEvent } from '@testing-library/user-event';

const updateServiceWorker: ReturnType<typeof vi.fn> = vi.fn();
const applyWaitingUpdate = vi.fn<() => Promise<boolean>>();
const reload: ReturnType<typeof vi.fn> = vi.fn();

vi.mock('@/lib/pwa/apply-waiting-update', () => ({
  applyWaitingUpdate: (): Promise<boolean> => applyWaitingUpdate(),
}));
let registeredOptions: {
  onRegisteredSW?: (url: string, registration?: { update: () => Promise<void> }) => void;
  onNeedReload?: () => void;
} = {};

/** Drives the two flags vite-plugin-pwa exposes, so a test can flip either. */
const state: { offlineReady: boolean; needRefresh: boolean; setOfflineReady: ReturnType<typeof vi.fn>; setNeedRefresh: ReturnType<typeof vi.fn> } = {
  offlineReady: false,
  needRefresh: false,
  setOfflineReady: vi.fn(),
  setNeedRefresh: vi.fn(),
};

vi.mock('virtual:pwa-register/react', () => ({
  useRegisterSW: (options: typeof registeredOptions) => {
    registeredOptions = options;
    return {
      offlineReady: [state.offlineReady, state.setOfflineReady],
      needRefresh: [state.needRefresh, state.setNeedRefresh],
      updateServiceWorker,
    };
  },
}));

const { PwaUpdatePrompt } = await import('../PwaUpdatePrompt');
const { Toaster } = await import('@/components/ui/sonner');

function setOnline(value: boolean): void {
  Object.defineProperty(navigator, 'onLine', { value, configurable: true });
}

/**
 * Toaster FIRST, exactly as App.tsx mounts it. Sonner drops any toast published
 * before a Toaster has subscribed, and effects run in mount order — so with the
 * prompt first, the update notice is raised into a void and nothing renders.
 * That is a real constraint on the app, not a test detail.
 */
function renderPrompt(): RenderResult {
  return render(
    <>
      <Toaster />
      <PwaUpdatePrompt />
    </>,
  );
}

// jsdom's location.reload is a no-op that warns; replacing it lets a test see
// whether the component reloaded, which is the whole question below.
Object.defineProperty(window, 'location', {
  configurable: true,
  value: { ...window.location, reload: () => reload() },
});

describe('PwaUpdatePrompt', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    applyWaitingUpdate.mockResolvedValue(true);
    setOnline(true);
    state.offlineReady = false;
    state.needRefresh = false;
    registeredOptions = {};
  });

  it('renders nothing itself — it drives the shared toast surface', () => {
    const { container } = render(<PwaUpdatePrompt />);

    expect(container).toBeEmptyDOMElement();
  });

  it('offers a reload when a new build is waiting', async () => {
    state.needRefresh = true;

    renderPrompt();

    expect(await screen.findByText('Update available')).toBeInTheDocument();
    expect(await screen.findByRole('button', { name: 'Reload' })).toBeInTheDocument();
  });

  it('applies the update when the user takes the offer', async () => {
    state.needRefresh = true;
    applyWaitingUpdate.mockResolvedValue(true);
    const user: UserEvent = userEvent.setup();

    renderPrompt();
    await user.click(await screen.findByRole('button', { name: 'Reload' }));

    expect(applyWaitingUpdate).toHaveBeenCalled();
    // The worker took control, so `controlling` fires and onNeedReload reloads
    // this window. Reloading here as well would race that.
    expect(reload).not.toHaveBeenCalled();
  });

  it('still reloads when another window already activated the update', async () => {
    // Once another window accepts, `registration.waiting` is null everywhere,
    // and messaging SKIP_WAITING to nothing is a silent no-op: `controlling`
    // never fires again. This window's original toast is still on screen, and
    // its Reload button did nothing whatsoever -- the toast dismissed and the
    // page stayed exactly where it was.
    state.needRefresh = true;
    applyWaitingUpdate.mockResolvedValue(false);
    const user: UserEvent = userEvent.setup();

    renderPrompt();
    await user.click(await screen.findByRole('button', { name: 'Reload' }));

    await vi.waitFor(() => expect(reload).toHaveBeenCalled());
  });

  it('does not arm a hard reload for the NEXT deploy when its own attempt found nothing', async () => {
    // The dangerous half. `weInitiatedUpdate` was set on click and never
    // cleared, so after a press that did nothing, the next release accepted in
    // another window hard-reloaded THIS one without asking -- dropping the
    // WebSocket and P2P state that prompt-mode exists to protect.
    state.needRefresh = true;
    applyWaitingUpdate.mockResolvedValue(false);
    const user: UserEvent = userEvent.setup();

    renderPrompt();
    await user.click(await screen.findByRole('button', { name: 'Reload' }));
    await vi.waitFor(() => expect(reload).toHaveBeenCalled());
    reload.mockClear();

    // The next deploy, accepted somewhere else.
    act(() => { registeredOptions.onNeedReload?.(); });

    expect(reload).not.toHaveBeenCalled();
    expect(await screen.findByText('Updated in another window')).toBeInTheDocument();
  });

  it('says nothing when there is no update', () => {
    renderPrompt();

    expect(screen.queryByText('Update available')).not.toBeInTheDocument();
  });

  it('confirms once the app can run offline', async () => {
    state.offlineReady = true;

    renderPrompt();

    expect(await screen.findByText('Ready to work offline')).toBeInTheDocument();
  });

  describe('checking for updates while a tab stays open', () => {
    // vite-plugin-pwa only checks at registration. This app is left open for
    // days, so without these a long-lived session never learns a deploy shipped.
    function registerWith(update: () => Promise<void>): void {
      renderPrompt();
      act(() => {
        registeredOptions.onRegisteredSW?.('/sw.js', { update });
      });
    }

    it('re-checks when the user comes back to the tab', () => {
      const update: ReturnType<typeof vi.fn> = vi.fn().mockResolvedValue(undefined);
      registerWith(update);

      Object.defineProperty(document, 'visibilityState', { value: 'visible', configurable: true });
      act(() => { document.dispatchEvent(new Event('visibilitychange')); });

      expect(update).toHaveBeenCalled();
    });

    it('re-checks when connectivity returns', () => {
      const update: ReturnType<typeof vi.fn> = vi.fn().mockResolvedValue(undefined);
      registerWith(update);

      act(() => { window.dispatchEvent(new Event('online')); });

      expect(update).toHaveBeenCalled();
    });

    it('does not check while offline, which could only fail', () => {
      const update: ReturnType<typeof vi.fn> = vi.fn().mockResolvedValue(undefined);
      registerWith(update);
      setOnline(false);

      Object.defineProperty(document, 'visibilityState', { value: 'visible', configurable: true });
      act(() => { document.dispatchEvent(new Event('visibilitychange')); });

      expect(update).not.toHaveBeenCalled();
    });

    it('stops listening once unmounted, so listeners cannot accumulate', () => {
      const update: ReturnType<typeof vi.fn> = vi.fn().mockResolvedValue(undefined);
      const { unmount } = renderPrompt();
      act(() => { registeredOptions.onRegisteredSW?.('/sw.js', { update }); });

      unmount();
      act(() => { window.dispatchEvent(new Event('online')); });

      expect(update).not.toHaveBeenCalled();
    });
  });
});

describe('an update accepted elsewhere does not reload this window', () => {
  // vite-plugin-pwa arms `controlling → window.location.reload()` unless
  // onNeedReload is supplied, and it arms it in EVERY window that saw the
  // waiting worker. skipWaiting takes over all clients at once, so one
  // window's click reloaded all of them — dropping each one's WebSocket, P2P
  // channels and in-flight document state mid-sentence. That is precisely the
  // guarantee registerType:'prompt' exists to provide.
  it('supplies onNeedReload so the library never reloads on its own', () => {
    // Reading the source, because the behaviour lives in the library's
    // callback and the option's PRESENCE is the whole fix: without it the
    // library reloads unconditionally.
    const source: string = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '..', 'PwaUpdatePrompt.tsx'),
      'utf8',
    );
    // Matches the OPTION, not the word: both files explain onNeedReload in a
    // comment, so `toContain('onNeedReload')` passes with the option deleted.
    // My first version of this test did exactly that and survived its own
    // negative control.
    expect(source).toMatch(/onNeedReload\s*:/);
    expect(source).toContain('weInitiatedUpdate.current');
  });

  it('marks this window as the initiator before skipping waiting', () => {
    const source: string = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '..', 'PwaUpdatePrompt.tsx'),
      'utf8',
    );
    // The flag must be set BEFORE the skip-waiting message, or the controlling
    // event can arrive first and this window declines its own reload.
    const setIndex: number = source.indexOf('weInitiatedUpdate.current = true');
    const callIndex: number = source.indexOf('applyWaitingUpdate()');
    expect(setIndex).toBeGreaterThan(-1);
    expect(callIndex).toBeGreaterThan(setIndex);
  });

  it('main.tsx does not arm a second, unowned reload', () => {
    // There are two registrations; main.tsx's exists so a crashed render still
    // receives updates. It must not also reload, since it owns no prompt.
    const main: string = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'main.tsx'),
      'utf8',
    );
    expect(main).toMatch(/onNeedReload\s*:/);
  });
});
