/**
 * The upgrade path. `registerType: 'prompt'` means a new build does NOTHING
 * until the user is offered a reload and takes it, so if this prompt is silent
 * an installed app sits on a stale bundle forever — the failure is invisible
 * precisely because nothing appears.
 *
 * The real Sonner surface is rendered rather than asserting on a mocked toast
 * call: the part most likely to break quietly is the action button, which only
 * exists if the `{label, onClick}` shape the component passes survives the
 * wrapper into Sonner. Asserting `toast` was called with the right object would
 * still pass if that contract broke.
 *
 * Only `virtual:pwa-register/react` is mocked — it is generated by the build and
 * cannot exist under vitest, and it is the seam the whole flow hangs from.
 */
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

const updateServiceWorker = vi.fn();
let registeredOptions: {
  onRegisteredSW?: (url: string, registration?: { update: () => Promise<void> }) => void;
} = {};

/** Drives the two flags vite-plugin-pwa exposes, so a test can flip either. */
const state = {
  offlineReady: false,
  needRefresh: false,
  setOfflineReady: vi.fn(),
  setNeedRefresh: vi.fn(),
};

vi.mock('virtual:pwa-register/react', () => ({
  useRegisterSW: (options: typeof registeredOptions) => {
    registeredOptions = options;
    return {
      offlineReady: [state.offlineReady, state.setOfflineReady],
      needRefresh: [state.needRefresh, state.setNeedRefresh],
      updateServiceWorker,
    };
  },
}));

const { PwaUpdatePrompt } = await import('../PwaUpdatePrompt');
const { Toaster } = await import('@/components/ui/sonner');

function setOnline(value: boolean) {
  Object.defineProperty(navigator, 'onLine', { value, configurable: true });
}

/**
 * Toaster FIRST, exactly as App.tsx mounts it. Sonner drops any toast published
 * before a Toaster has subscribed, and effects run in mount order — so with the
 * prompt first, the update notice is raised into a void and nothing renders.
 * That is a real constraint on the app, not a test detail.
 */
function renderPrompt() {
  return render(
    <>
      <Toaster />
      <PwaUpdatePrompt />
    </>,
  );
}

describe('PwaUpdatePrompt', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    setOnline(true);
    state.offlineReady = false;
    state.needRefresh = false;
    registeredOptions = {};
  });

  it('renders nothing itself — it drives the shared toast surface', () => {
    const { container } = render(<PwaUpdatePrompt />);

    expect(container).toBeEmptyDOMElement();
  });

  it('offers a reload when a new build is waiting', async () => {
    state.needRefresh = true;

    renderPrompt();

    expect(await screen.findByText('Update available')).toBeInTheDocument();
    expect(await screen.findByRole('button', { name: 'Reload' })).toBeInTheDocument();
  });

  it('applies the update when the user takes the offer', async () => {
    state.needRefresh = true;
    const user = userEvent.setup();

    renderPrompt();
    await user.click(await screen.findByRole('button', { name: 'Reload' }));

    // `true` is the load-bearing argument: it tells the waiting worker to
    // activate and reload. Calling it without one swaps nothing.
    expect(updateServiceWorker).toHaveBeenCalledWith(true);
  });

  it('says nothing when there is no update', () => {
    renderPrompt();

    expect(screen.queryByText('Update available')).not.toBeInTheDocument();
  });

  it('confirms once the app can run offline', async () => {
    state.offlineReady = true;

    renderPrompt();

    expect(await screen.findByText('Ready to work offline')).toBeInTheDocument();
  });

  describe('checking for updates while a tab stays open', () => {
    // vite-plugin-pwa only checks at registration. This app is left open for
    // days, so without these a long-lived session never learns a deploy shipped.
    function registerWith(update: () => Promise<void>) {
      renderPrompt();
      act(() => {
        registeredOptions.onRegisteredSW?.('/sw.js', { update });
      });
    }

    it('re-checks when the user comes back to the tab', () => {
      const update = vi.fn().mockResolvedValue(undefined);
      registerWith(update);

      Object.defineProperty(document, 'visibilityState', { value: 'visible', configurable: true });
      act(() => { document.dispatchEvent(new Event('visibilitychange')); });

      expect(update).toHaveBeenCalled();
    });

    it('re-checks when connectivity returns', () => {
      const update = vi.fn().mockResolvedValue(undefined);
      registerWith(update);

      act(() => { window.dispatchEvent(new Event('online')); });

      expect(update).toHaveBeenCalled();
    });

    it('does not check while offline, which could only fail', () => {
      const update = vi.fn().mockResolvedValue(undefined);
      registerWith(update);
      setOnline(false);

      Object.defineProperty(document, 'visibilityState', { value: 'visible', configurable: true });
      act(() => { document.dispatchEvent(new Event('visibilitychange')); });

      expect(update).not.toHaveBeenCalled();
    });

    it('stops listening once unmounted, so listeners cannot accumulate', () => {
      const update = vi.fn().mockResolvedValue(undefined);
      const { unmount } = renderPrompt();
      act(() => { registeredOptions.onRegisteredSW?.('/sw.js', { update }); });

      unmount();
      act(() => { window.dispatchEvent(new Event('online')); });

      expect(update).not.toHaveBeenCalled();
    });
  });
});
