import type { ThemePalette } from './theme-types';

/**
 * Avarok Purple — the theme the product already ships.
 *
 * Transcribed literally from the tokens in index.css rather than rebuilt from a
 * seed. Every other preset is generated by `buildPalette`, but this one must
 * reproduce the current appearance EXACTLY: it is the default, and a
 * "regenerated" version that came out a shade different would silently restyle
 * the whole app the moment theming shipped.
 *
 * The values carry their original reasoning:
 *  - light `primary` at 45% lightness gives ~7:1 on white and ~6.6:1 for white
 *    text on it, so the fill works in both directions.
 *  - dark `mutedForeground` is 72%, not 54%: at 54% it rendered 3.49:1 on the
 *    card surface, under the 4.5:1 AA floor, which Lighthouse flagged on every
 *    toast description.
 */

export const AVAROK_LIGHT: ThemePalette = {
  background: { h: 0, s: 0, l: 100 },
  foreground: { h: 235, s: 18, l: 13 },
  card: { h: 240, s: 20, l: 99 },
  cardForeground: { h: 235, s: 18, l: 13 },
  popover: { h: 0, s: 0, l: 100 },
  popoverForeground: { h: 235, s: 18, l: 13 },
  surface: { h: 240, s: 20, l: 96 },
  surfaceForeground: { h: 235, s: 18, l: 13 },

  primary: { h: 257, s: 45, l: 45 },
  primaryForeground: { h: 0, s: 0, l: 100 },
  primaryAccent: { h: 257, s: 45, l: 42 },

  secondary: { h: 240, s: 20, l: 96 },
  secondaryForeground: { h: 235, s: 18, l: 13 },
  muted: { h: 240, s: 20, l: 96 },
  mutedForeground: { h: 235, s: 12, l: 38 },
  accent: { h: 240, s: 20, l: 94 },
  accentForeground: { h: 235, s: 18, l: 13 },

  destructive: { h: 0, s: 72, l: 45 },
  destructiveForeground: { h: 0, s: 0, l: 100 },
  success: { h: 160, s: 84, l: 28 },
  successForeground: { h: 0, s: 0, l: 100 },
  // 33%, not 38%: white on 38% is 3.60:1. Every warning banner carries this.
  warning: { h: 38, s: 92, l: 33 },
  warningForeground: { h: 0, s: 0, l: 100 },

  border: { h: 240, s: 15, l: 88 },
  input: { h: 240, s: 20, l: 97 },
  ring: { h: 257, s: 45, l: 45 },
};

export const AVAROK_DARK: ThemePalette = {
  background: { h: 235, s: 18, l: 13 },
  foreground: { h: 0, s: 0, l: 100 },
  card: { h: 234, s: 21, l: 17 },
  cardForeground: { h: 0, s: 0, l: 100 },
  popover: { h: 234, s: 21, l: 17 },
  popoverForeground: { h: 0, s: 0, l: 100 },
  surface: { h: 230, s: 32, l: 22 },
  surfaceForeground: { h: 0, s: 0, l: 100 },

  primary: { h: 257, s: 30, l: 50 },
  primaryForeground: { h: 0, s: 0, l: 100 },
  primaryAccent: { h: 251, s: 85, l: 75 },

  secondary: { h: 234, s: 21, l: 17 },
  secondaryForeground: { h: 0, s: 0, l: 100 },
  muted: { h: 234, s: 21, l: 17 },
  mutedForeground: { h: 265, s: 25, l: 72 },
  accent: { h: 230, s: 32, l: 22 },
  accentForeground: { h: 0, s: 0, l: 100 },

  // 50%, not the 60% this used to be: white on the lighter red measured 3.78:1,
  // under the 4.5:1 WCAG AA needs for normal text, so every destructive button
  // in dark mode failed. 50% measures 4.53:1. Kept in step with index.css, which
  // the test below asserts verbatim.
  destructive: { h: 0, s: 84, l: 50 },
  destructiveForeground: { h: 0, s: 0, l: 100 },
  success: { h: 160, s: 84, l: 39 },
  // Ink, not white: white on this green is 2.59:1, while ink is 6.51:1. Dark
  // `warning` below already takes ink for the same reason — a vivid status
  // colour in a dark theme is light enough that dark text is the readable pair.
  successForeground: { h: 235, s: 18, l: 13 },
  warning: { h: 38, s: 92, l: 50 },
  warningForeground: { h: 235, s: 18, l: 13 },

  border: { h: 222, s: 23, l: 23 },
  input: { h: 235, s: 25, l: 10 },
  ring: { h: 251, s: 85, l: 75 },
};

/** Corner rounding the product ships with, in rem. */
export const AVAROK_RADIUS = 0.75;
