// GENERATED by scripts/sync-brand-kit.mjs in the parent repository from assets/brand/tokens/brand.json and site.webmanifest.
// Do not edit: change the kit and re-run the sync. scripts/check-brand-kit-is-synced.mjs fails on drift.

export const BRAND_NAME: "Citadel Workspaces" = "Citadel Workspaces";
export const BRAND_SHORT_NAME: "Citadel" = "Citadel";

/** CSS pixels. Lockups are measured across, the mark by its height. */
export const MINIMUM_SIZE: {
  readonly markPx: number;
  readonly compactBelowPx: number;
  readonly horizontalPx: number;
  readonly wordmarkPx: number;
  readonly stackedPx: number;
} = {
  markPx: 16,
  compactBelowPx: 32,
  horizontalPx: 120,
  wordmarkPx: 96,
  stackedPx: 96,
};

/** The logo's two colour roles on each ground. styles/brand-tokens.css must carry these. */
export const BRAND_COLOURS: {
  readonly light: { readonly ink: string; readonly arrow: string };
  readonly dark: { readonly ink: string; readonly arrow: string };
} = {
  light: { ink: "#1C1D28", arrow: "#6E59A5" },
  dark: { ink: "#FFFFFF", arrow: "#9B87F5" },
};
