// GENERATED by scripts/sync-brand-kit.mjs in the parent repository from assets/brand/svg/mark.svg.
// Do not edit: change the kit and re-run the sync. scripts/check-brand-kit-is-synced.mjs fails on drift.
import type { BrandArtwork } from './brand-artwork';

export const MARK: BrandArtwork = {
  viewBox: "33 17 136 150",
  width: 136,
  height: 150,
  strokeWidth: 14,
  clearSpace: 46,
  arc: "M142.43 142.43A60 60 0 1 1 100 40",
  arrow: "M100 40H162M146 24L162 40L146 56",
  glyphs: null,
};
