// GENERATED by scripts/sync-brand-kit.mjs in the parent repository from assets/brand/svg/mark-compact.svg.
// Do not edit: change the kit and re-run the sync. scripts/check-brand-kit-is-synced.mjs fails on drift.
import type { BrandArtwork } from './brand-artwork';

export const MARK_COMPACT: BrandArtwork = {
  viewBox: "31 14.76 138 154.24",
  width: 138,
  height: 154.24,
  strokeWidth: 22,
  clearSpace: 46,
  arc: "M141.01 141.01A58 58 0 1 1 100 42",
  arrow: "M100 42H158M141.76 25.76L158 42L141.76 58.24",
  glyphs: null,
};
