/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const close_connection: () => any;
export const ensure_messenger_open: (a: number, b: number) => any;
export const get_version: () => [number, number];
export const init: (a: number, b: number) => any;
export const is_initialized: () => number;
export const main: () => void;
export const next_message: () => any;
export const open_messenger_for: (a: number, b: number) => any;
export const restart: (a: number, b: number) => any;
export const send_direct_to_internal_service: (a: any) => any;
export const send_p2p_message_reliable: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const wasm_bindgen__convert__closures_____invoke__hdd61e8d0c040105f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hb3b762a8165c6006: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1091a2bd61c67144: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h57846bf0feebf189: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc8adb55dc8d53303: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hef3cbac11a7756ae: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfc7969a467461df8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h635057cf238ab386: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h54a98780339cd665: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
